version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: rikkei_prod
      POSTGRES_USER: user_rikkei
      POSTGRES_PASSWORD: password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rikkei_network

  # Backend Service (Spring Boot)
  backend:
    build: ./backend
    container_name: spring_backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rikkei_prod
      SPRING_DATASOURCE_USERNAME: user_rikkei
      SPRING_DATASOURCE_PASSWORD: password_123
    networks:
      - rikkei_network
    ports:
      - "8080:8080"

  # Frontend Service (ReactJS)
  frontend:
    build: ./frontend
    container_name: react_frontend
    networks:
      - rikkei_network
    ports:
      - "80:80"

networks:
  rikkei_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
